dsp:
  addr: 3
  host: 192.168.1.230
  input:
    '0': True
    '1': False
    '2': False
    '3': False
  output:
    '0': True
    '1': False
    '2': False
    '3': False
    '4': False
    '5': False
    '6': False
    '7': False
  port: 4196
projector:
  host: 192.168.1.220
  nic_warmup_s: 12
  password: '1234'
  pjlink_retries: 4
  pjlink_timeout_s: 8
  port: 4352
  post_power_on_delay_s: 1.5
shelly1:
  base: http://192.168.1.10
  ch1: 0
  ch2: 1
shelly2:
  base: http://192.168.1.11
  ch1: 0
  ch2: 1
